from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_cliente(object):
    def setupUi(self, cliente):
        cliente.setObjectName("cliente")
        cliente.resize(640, 480)
        cliente.setMinimumSize(QtCore.QSize(640, 480))
        cliente.setMaximumSize(QtCore.QSize(640, 480))
        self.frame_titulo = QtWidgets.QFrame(parent=cliente)
        self.frame_titulo.setGeometry(QtCore.QRect(0, 0, 640, 80))
        self.frame_titulo.setMinimumSize(QtCore.QSize(640, 80))
        self.frame_titulo.setMaximumSize(QtCore.QSize(640, 80))
        self.frame_titulo.setStyleSheet("background-color: rgb(0, 170, 0);")
        self.frame_titulo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_titulo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_titulo.setObjectName("frame_titulo")
        self.label_titulo = QtWidgets.QLabel(parent=self.frame_titulo)
        self.label_titulo.setGeometry(QtCore.QRect(0, 0, 640, 80))
        self.label_titulo.setMinimumSize(QtCore.QSize(640, 80))
        self.label_titulo.setMaximumSize(QtCore.QSize(640, 80))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        self.label_titulo.setFont(font)
        self.label_titulo.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_titulo.setObjectName("label_titulo")
        self.frame_rodape = QtWidgets.QFrame(parent=cliente)
        self.frame_rodape.setGeometry(QtCore.QRect(0, 400, 640, 80))
        self.frame_rodape.setMinimumSize(QtCore.QSize(640, 80))
        self.frame_rodape.setMaximumSize(QtCore.QSize(640, 80))
        self.frame_rodape.setStyleSheet("background-color: rgb(236, 255, 193);")
        self.frame_rodape.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_rodape.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_rodape.setObjectName("frame_rodape")
        self.frame_corpo = QtWidgets.QFrame(parent=cliente)
        self.frame_corpo.setGeometry(QtCore.QRect(0, 80, 640, 320))
        self.frame_corpo.setMinimumSize(QtCore.QSize(640, 320))
        self.frame_corpo.setMaximumSize(QtCore.QSize(640, 320))
        self.frame_corpo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_corpo.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_corpo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_corpo.setObjectName("frame_corpo")
        self.lineEdit_nome = QtWidgets.QLineEdit(parent=self.frame_corpo)
        self.lineEdit_nome.setGeometry(QtCore.QRect(130, 70, 250, 20))
        self.lineEdit_nome.setMinimumSize(QtCore.QSize(250, 20))
        self.lineEdit_nome.setMaximumSize(QtCore.QSize(250, 20))
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.lineEdit_cpf = QtWidgets.QLineEdit(parent=self.frame_corpo)
        self.lineEdit_cpf.setGeometry(QtCore.QRect(130, 110, 100, 20))
        self.lineEdit_cpf.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit_cpf.setMaximumSize(QtCore.QSize(100, 20))
        self.lineEdit_cpf.setObjectName("lineEdit_cpf")
        self.label = QtWidgets.QLabel(parent=self.frame_corpo)
        self.label.setGeometry(QtCore.QRect(70, 70, 49, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_corpo)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 49, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_buscar = QtWidgets.QLineEdit(parent=self.frame_corpo)
        self.lineEdit_buscar.setGeometry(QtCore.QRect(130, 20, 100, 20))
        self.lineEdit_buscar.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit_buscar.setMaximumSize(QtCore.QSize(100, 20))
        self.lineEdit_buscar.setObjectName("lineEdit_buscar")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_corpo)
        self.label_3.setGeometry(QtCore.QRect(70, 20, 49, 16))
        self.label_3.setObjectName("label_3")
        self.bt_inserir = QtWidgets.QPushButton(parent=self.frame_corpo)
        self.bt_inserir.setGeometry(QtCore.QRect(70, 230, 90, 50))
        self.bt_inserir.setMinimumSize(QtCore.QSize(90, 50))
        self.bt_inserir.setMaximumSize(QtCore.QSize(90, 50))
        self.bt_inserir.setStyleSheet("background-color: rgb(220, 255, 174);")
        self.bt_inserir.setObjectName("bt_inserir")
        self.bt_editar = QtWidgets.QPushButton(parent=self.frame_corpo)
        self.bt_editar.setGeometry(QtCore.QRect(180, 230, 90, 50))
        self.bt_editar.setMinimumSize(QtCore.QSize(90, 50))
        self.bt_editar.setMaximumSize(QtCore.QSize(90, 50))
        self.bt_editar.setStyleSheet("background-color: rgb(255, 252, 207);")
        self.bt_editar.setObjectName("bt_editar")
        self.bt_buscar = QtWidgets.QPushButton(parent=self.frame_corpo)
        self.bt_buscar.setGeometry(QtCore.QRect(280, 230, 90, 50))
        self.bt_buscar.setMinimumSize(QtCore.QSize(90, 50))
        self.bt_buscar.setMaximumSize(QtCore.QSize(90, 50))
        self.bt_buscar.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.bt_buscar.setObjectName("bt_buscar")
        self.bt_excluir = QtWidgets.QPushButton(parent=self.frame_corpo)
        self.bt_excluir.setGeometry(QtCore.QRect(390, 230, 90, 50))
        self.bt_excluir.setMinimumSize(QtCore.QSize(90, 50))
        self.bt_excluir.setMaximumSize(QtCore.QSize(90, 50))
        self.bt_excluir.setStyleSheet("background-color: rgb(255, 116, 116);")
        self.bt_excluir.setObjectName("bt_excluir")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_corpo)
        self.label_4.setGeometry(QtCore.QRect(70, 140, 49, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_foto = QtWidgets.QLineEdit(parent=self.frame_corpo)
        self.lineEdit_foto.setGeometry(QtCore.QRect(130, 140, 200, 20))
        self.lineEdit_foto.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit_foto.setMaximumSize(QtCore.QSize(200, 20))
        self.lineEdit_foto.setObjectName("lineEdit_foto")
        self.bt_foto = QtWidgets.QPushButton(parent=self.frame_corpo)
        self.bt_foto.setGeometry(QtCore.QRect(350, 140, 40, 20))
        self.bt_foto.setMinimumSize(QtCore.QSize(40, 20))
        self.bt_foto.setMaximumSize(QtCore.QSize(40, 20))
        self.bt_foto.setObjectName("bt_foto")
        self.lb_foto = QtWidgets.QLabel(parent=self.frame_corpo)
        self.lb_foto.setGeometry(QtCore.QRect(460, 20, 150, 150))
        self.lb_foto.setMinimumSize(QtCore.QSize(150, 150))
        self.lb_foto.setMaximumSize(QtCore.QSize(150, 150))
        self.lb_foto.setStyleSheet("border: 1px solid ;")
        self.lb_foto.setObjectName("lb_foto")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_corpo)
        self.label_5.setGeometry(QtCore.QRect(70, 170, 49, 16))
        self.label_5.setObjectName("label_5")
        self.cb_produto = QtWidgets.QComboBox(parent=self.frame_corpo)
        self.cb_produto.setGeometry(QtCore.QRect(170, 170, 200, 20))
        self.cb_produto.setMinimumSize(QtCore.QSize(200, 20))
        self.cb_produto.setMaximumSize(QtCore.QSize(200, 20))
        self.cb_produto.setObjectName("cb_produto")
        self.lineEdit_cod = QtWidgets.QLineEdit(parent=self.frame_corpo)
        self.lineEdit_cod.setGeometry(QtCore.QRect(130, 170, 30, 20))
        self.lineEdit_cod.setMinimumSize(QtCore.QSize(30, 20))
        self.lineEdit_cod.setMaximumSize(QtCore.QSize(30, 20))
        self.lineEdit_cod.setObjectName("lineEdit_cod")

        self.retranslateUi(cliente)
        QtCore.QMetaObject.connectSlotsByName(cliente)

    def retranslateUi(self, cliente):
        _translate = QtCore.QCoreApplication.translate
        cliente.setWindowTitle(_translate("cliente", "Form"))
        self.label_titulo.setText(_translate("cliente", "Controle de Clientes"))
        self.label.setText(_translate("cliente", "Nome:"))
        self.label_2.setText(_translate("cliente", "CPF:"))
        self.label_3.setText(_translate("cliente", "Buscar:"))
        self.bt_inserir.setText(_translate("cliente", "Inserir"))
        self.bt_editar.setText(_translate("cliente", "Editar"))
        self.bt_buscar.setText(_translate("cliente", "Buscar"))
        self.bt_excluir.setText(_translate("cliente", "Excluir"))
        self.label_4.setText(_translate("cliente", "Foto:"))
        self.bt_foto.setText(_translate("cliente", "..."))
        self.lb_foto.setText(_translate("cliente", "Foto:"))
        self.label_5.setText(_translate("cliente", "Produto:"))